[project]
authors = ["Alistair Miles <alimanfoo@googlemail.com>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "2024-08-14-terms-of-use-metadata"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "~=3.12"
google-cloud-sdk = ">=490.0.0,<491"

[pypi-dependencies]
malariagen-data = ">=13.0.0, <14"
jupyterlab = ">=4.2.5, <5"
nbconvert = ">=7.16.4, <8"
