[project]
authors = ["Alistair Miles <alimanfoo@googlemail.com>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "2024-06-06-sequence-qc-metadata"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "~=3.12"

[pypi-dependencies]
jupyterlab = ">=4.2.5, <5"
nbconvert = ">=7.16.4, <8"
malariagen-data = ">=13.0.0, <14"
