[project]
authors = ["KellyLBennett <kellylb13@yahoo.com>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "2023-10-26-early-data-release"
platforms = ["osx-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "3.11.*"
jupyterlab = ">=4.3.1,<5"
nbconvert = ">=7.16.4,<8"
plotly = ">=5.24.1,<6"
pandas = ">=2.2.3,<3"
bokeh = ">=3.6.1,<4"
